### ISSUE TITLE
App looks frozen when searching through the large logs 

### ISSUE THREAD

**Issue by EkaterinaValeeva** [annikovk/IntelliJ-Log-Analyzer#11]
v1.0.5, Windows 10
*STR*:
1. Load log.zip from [this ZD issue](https://jbs.zendesk.com/agent/tickets/3817407)
2. Start typing "FREEZE".

*Result*:
Only "F" gets typed, the input field becomes unresponsive with no visual indication that some process is running internally. However after some time (~30-40 s) it wakes up and highlights the search results properly. 
It took me several restarts to stop closing the app and just wait until it's ready :)

It would be great to display some "loading search results please wait" if it's not possible to avoid locking the UI.

P.S. Thank you for your efforts, the whole thing looks very promising.

**Comment by annikovk** [comment]
As a workaround, search will be reversed (end to begin): 
https://github.com/annikovk/IntelliJ-Log-Analyzer/commit/f24e8ff4c0b9fc1c97b1f56219488f2ba98d82f0#diff-cc03dbadff8df5dba6164d3ac81725881d35492335ec496421aef11a085b140dR117

This should prevent highlighting of folded regions, which causes freeze. 

Further improvements require https://github.com/ajaxorg/ace/issues/4687 to be fixed. I'll monitor it.
