### ISSUE TITLE
Color square for Indexing diagnostic goes to the next line

### ISSUE THREAD

**Issue by EkaterinaValeeva** [annikovk/IntelliJ-Log-Analyzer#12]
v1.0.5, Windows 10, screen 2560 x 1600, 150% scaling / 3840 x 2160, 200% scaling (recommended for my laptop)

After I start the app the square appears on the next line in the dedicated pane so I need to drag the right border to make it fit.

![image](https://user-images.githubusercontent.com/29943172/166481063-e4dd33f6-07ca-4132-9103-9b3e9ee71184.png)

Maybe it would make sense to highlight the whole line with the corresponding color instead of showing it separately, like this:

![image](https://user-images.githubusercontent.com/29943172/166483165-f0e9b561-0351-4d50-a32c-d036fead8ad3.png)

**Comment by annikovk** [comment]
Good idea. Done: 
https://github.com/annikovk/IntelliJ-Log-Analyzer/commit/f6855152391ca77ab6ff334d749633a9ebbf302e

Will be included in 1.0.6 and published later today.
