### ISSUE TITLE
Freeze dumps not listed in other files section

### ISSUE THREAD

**Issue by egorklepikov** [annikovk/IntelliJ-Log-Analyzer#18]
Jumping to thread-dump using links directly from the logs is useful, but often there are dozens of reports of freezes in the archive and it is not convenient to search each of them in the logs to see. Especially if you need to understand the overall picture of the problem.

Here is an example on how it's done in VSCode:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/34603633/175907854-b93d8bbc-94f6-4bb1-87b0-591c599dc122.png">

If this feature will be considered to implement here is one more enhancement: provide an ability to jump to the corresponding `FREEZE — Freeze started` entry in idea.log file directly from threadDump report.

**Comment by annikovk** [comment]
Implemented like this: 
![Screen Recording 2022-07-06 at 20 08 16](https://user-images.githubusercontent.com/12910542/177616214-83c0a6cd-f7b8-401a-b474-413d95d85bf4.gif)


Now you can focus entry at timeline from the files list

**Comment by egorklepikov** [comment]
Thank you! Looks nice. On my laptop it works quite slow comparing to what you attached in demo. Uploaded a screencast and the logs at 2022_07_07_CWHNYPvGM13Fq52VZP8S1y
